config/routes.rb
Unite::Application.routes.draw do
  get "static_pages/help"

  devise_for :users

  resources :users do
    member do
      get :general_info, :groups, :subscriptions, :activities, :notifications, :invites
      post :invite_reply
    end
  end

  resources :categories
  resources :subscriptions, only: [:create, :destroy]
  resources :activities 
  resources :participations, only: [:create, :destroy]
  resources :groups do
    member do
      post :invite
    end
  end
  resources :group_memberships, only: [:create, :destroy]  
  resources :comments

  root to: "activities#index", category_id: 13
  match '/help', to: 'static_pages#help'

end

app/models/group.rb
class Group < ActiveRecord::Base
	attr_accessible :details, :name, :open_to_public

	has_many :group_memberships, foreign_key: "group_id"
	has_many :members, through: :group_memberships

	has_many :activity_group_relations, foreign_key: "group_id"
	has_many :activities, through: :activity_group_relations

	after_create :auto_add_creator_to_members

	validates :name, 			presence: true, uniqueness: { case_sensitive: false }
	validates :creator_id, 		presence: true

  
	def self.search(search)
	  	if !search.blank?
	  		conditions = ["name LIKE (?) AND open_to_public = ?", "%#{search}%", true]
	  	else
	  		conditions = ["open_to_public = ?", true]
	  	end
	     find(:all, conditions: conditions)
	end

	private
	    def auto_add_creator_to_members
	      creator = User.find(self.creator_id)
	      creator.join_group!(self)
	    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :group_creator, only: [:edit, :update, :destroy]

  def index
    @groups = Group.paginate(per_page: 10, page: params[:page]).search(params[:search])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])
    @group.creator_id = current_user.id
    if @group.save
      flash[:success] = "Successfully created group: #{@group.name}"
      redirect_to groups_path
    else
      flash[:error] = "there was a problem: #{@activity.errors.full_messages}"
      render 'new'
    end
  end

  def show
    @group = Group.find(params[:id])
    begin
      creator = User.find(@group.creator_id)
      @creator_string = creator.username
    rescue
      @creator_string = "The creator of this group is no longer a user of 'IT'S ON!'"
    end

    conditions = "groups.id = (?)", @group.id
    @members = User.paginate(per_page: 10, page: params[:page]).all(
                                                joins: { :groups => :group_memberships},
                                                conditions: conditions,
                                                group: 'users.id',
                                                order: 'users.username')
    #same conditions here
    @activities = Activity.paginate(per_page: 10, page: params[:page]).all(
                                                joins: {:groups => :activity_group_relations},
                                                conditions: conditions,
                                                group: 'activities.id',
                                                order: 'activities.date_and_time')
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      flash[:success] = "Group updated"
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def invite
    @group = Group.find(params[:group_id])
    if params[:emails] != ""
      @emails = params[:emails].split(",")
      #check for email validity
      email_format = %r([a-z0-9!#$&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+(?:[A-Z]{2}|com|org|net|edu|gov|mil|biz|info|mobi|name|aero|asia|jobs|museum)\b)
      for email in @emails do
        if email.match(email_format).nil?
          flash[:error] = "At least one email address is invalid"
          redirect_to :back and return
          break
        end
      end
      send_invite_emails(@group, @emails)
      flash[:success] = "Invites successfully sent."
      redirect_to :back
    else
      flash[:error] = "Must provide at least 1 VALID email address"
      redirect_to :back
    end
  end

  def destroy
    group = Group.find(params[:id])
    
    #delete all memebership associations for this group
    group.group_memberships.each do |membership|
      membership.destroy
    end

    #delete all activity-group-relations for this group
    group.activity_group_relations.each do |agr|
      agr.destroy
    end

    group.destroy
    flash[:success]= "Successfully deleted group."
    redirect_to groups_path
  end

  private
    def group_creator
      group = Group.find(params[:id])
      begin 
        creator = User.find(group.creator_id)
        redirect_to groups_path unless creator == current_user || current_user.admin?
      rescue
        redirect_to groups_path unless current_user.admin?
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper

	def get_group_row_class(group)
		if signed_in? && current_user.member?(group)
			if group.open_to_public?
				"group-member"
			else
				"group-member private-group"
			end
		end
	end

	def send_invite_emails(group, emails)
		for email in emails do
			invite = Invite.new(group_id: group.id, host_id: current_user.id, guest_email: email)
			invite.save
			UserMailer.group_invite(email, group).deliver
		end
	end
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.label "Open to the public", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :open_to_public, checked_value: true, unchecked_value: false %><br /><br />
    </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :details, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :details, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                groups_path, :class => 'btn' %>
  </div>
<% end %>

app/views/groups/_group_actions.html.erb
<% if signed_in? %>
	<span class="action-buttons">
		<% if !current_user.member?(group) %>
			<%= render partial: 'join_button', locals: { group: group } %>
		<% else %>
			<%= render partial: 'leave_button', locals: { group: group } %>		
		<% end %>
		<% if group.creator_id == current_user.id %>
			<%= link_to t('.edit', :default => t("helpers.links.edit")),
			              edit_group_path(group), :class => 'btn btn-mini' %>
			<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
			          group_path(group),
			          :method => :delete,
			          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
			          :class => 'btn btn-mini btn-danger' %>
		<% end %>
	</span>
<% end %>

app/views/groups/_join_button.html.erb
<%= form_for(current_user.group_memberships.build(group_id: group.id),
	html: { class: "inline-form" }) do |f| %>
  <div><%= f.hidden_field :group_id %></div>
  <%= image_submit_tag "join.jpg", class: "subscribe-button inline", title: "join" %>
<% end %>

app/views/groups/_leave_button.html.erb
<%= form_for(current_user.group_memberships.find_by_group_id(group.id),
            html: { method: :delete, class: "inline-form" }) do |f| %>
  <%= image_submit_tag "leave.png", class: "subscribe-button inline", title: "leave group" %>
<% end %>

app/views/groups/_user_subscriptions.html.erb
<div class="page-header">
  <h3>Subscriptions</h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <% if signed_in? && @user == current_user %>
      	<th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user.subscriptions.each do |group| %>
	    <tr class=<%= get_group_row_class(group) %>>
	      <td><%= group.name %></td>
          <td>
          	<% if signed_in? && @user == current_user && group.id != 1 %>
	            <%= form_for(current_user.group_memberships.find_by_group_id(group.id),
	            	html: { method: :delete, class: "inline-form" }) do |f| %>
					<%= f.submit "LEAVE", class: "btn btn-mini" %>
				<% end %>
			<% end %>
          </td>
	    </tr>
	<% end %>
  </tbody>
</table>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/edit.html.erb
<% provide(:title, 'Edit Group') %>

<%- model_class = Group -%>
<div class="main-area">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>

	<%= render :partial => 'form' %>
</div>

app/views/groups/index.html.erb
<% provide(:title, 'Groups') %>

<div class="instruction-question">How do groups work?</div>
<p>Groups allow users to keep an activity private to just the users of the group.  To create a new group, just click on the "New" button at the bottom of the group list.  To join a group, simply click on the '+' icon for that group.</p><br />

<%- model_class = Group -%>
<div class="main-area">
  <div class="row">
    <h1 class="span4">
      Public Groups
    </h1>
    <div class="pull-right inline">
      <%= form_tag groups_path, method: 'get' do %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:details) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <% if group.id != 1 %>
          <tr class=<%= get_group_row_class(group) %>>
            <td><%= link_to_group(group) %></td>
            <td><%= group.details %></td>
            <td><%= group.created_at %></td>
            <td>
              <%= render partial: 'group_actions', locals: { group: group } %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <% if signed_in? %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_group_path,
                :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/groups/new.html.erb
<% provide(:title, 'New Group') %>

<%- model_class = Group -%>
<div class="main-area">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
	<%= render :partial => 'form' %>
</div>

app/views/groups/show.html.erb
<% provide(:title, 'Group Details') %>

<%- model_class = Group -%>
<div class="main-area">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>

  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= @group.name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:creator) %>:</strong></dt>
    <dd><%= @creator_string %></dd>
    <dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt>
    <dd><%= @group.details %></dd>
    <dt><strong><%= model_class.human_attribute_name(:open_to_public) %>:</strong></dt>
    <dd><%= @group.open_to_public %></dd>
  </dl>
  <br />


  <h3 class="inline">Members</h3>
  <div class="list-users">
    <table class="table table-striped">
      <tbody>
        <% @members.each do |member| %>
        <tr>
          <td><%= link_to "#{member.username}", general_info_user_path(member) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if !@group.open_to_public && current_user.member?(@group) %>
    <%= form_tag invite_group_path, class: "inline" do %>
          <%= text_field_tag :emails, params[:emails] %>
          <%= hidden_field_tag :group_id, params[:id] %>
          <%= submit_tag "Invite", name: nil, class: "btn btn-mini btn-primary" %> 
          (Enter emails seperated by commas)<br />
    <% end %>
  <% end %>

  <%= will_paginate @members %>
  <br />

  <h3>Activities</h3>
  <div class="list-activities">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Category</th>
          <th>Title</th>
          <th>Date</th>
          <th>Where</th>
        </tr>
      </thead>
      <tbody>
        <% @activities.each do |activity| %>
        <tr>
          <% category = Category.find(activity.category_id) %>
          <td><%= category.name %></td>
          <td><%= activity.title %></td>
          <td><%= activity.date_and_time.strftime("%b %d") %></td>
          <td><%= activity.where %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= will_paginate @activities %>

  <% if signed_in? %>
    <% if (current_user.id == @group.creator_id) || current_user.admin? %>
      <div class="form-actions">
        <%= link_to t('.back', :default => t("helpers.links.back")),
                    groups_path, :class => 'btn'  %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_group_path(@group), :class => 'btn' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    group_path(@group),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger' %>
        <p class="inline"> *** You were the creator of this group *** </p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/groups/update.html.erb
<h1>Groups#update</h1>
<p>Find me in app/views/groups/update.html.erb</p>