config/routes.rb
Unite::Application.routes.draw do
  get "static_pages/help"

  devise_for :users

  resources :users do
    member do
      get :general_info, :groups, :subscriptions, :activities, :notifications, :invites
      post :invite_reply
    end
  end

  resources :categories
  resources :subscriptions, only: [:create, :destroy]
  resources :activities 
  resources :participations, only: [:create, :destroy]
  resources :groups do
    member do
      post :invite
    end
  end
  resources :group_memberships, only: [:create, :destroy]  
  resources :comments

  root to: "activities#index", category_id: 13
  match '/help', to: 'static_pages#help'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,   #added by devise
  				  :first_name, :last_name, :username, :age, :zipcode,		           #general info
            :public_distance_notf_max,  #max distance to notify for public activities
            :notf_new_activity, :notf_activity_turns_on, :notf_new_comment   #notifications

  geocoded_by :zipcode
  after_validation :geocode
  				 
  #Activity participation associations
  has_many :participations, foreign_key: "user_id"
  has_many :activities, through: :participations

  #Group membership associations
  has_many :group_memberships, foreign_key: "member_id"
  has_many :groups, through: :group_memberships

  #Category subscription associations
  has_many :subscriptions, foreign_key: "subscriber_id"
  has_many :categories, through: :subscriptions

  #Comment associations
  has_many :comments

  #validations
  validates :username,  			presence: true,  uniqueness: { case_sensitive: false }
  validates :age,       			presence: true
  validates :zipcode,   			presence: true

  after_create :add_to_public_group

  # attr_accessible :title, :body

  #Activity association methods ##############################################
  def participating?(activity)
    self.participations.find_by_activity_id(activity.id)
  end

  def participate!(activity)
    self.participations.create!(activity_id: activity.id)
  end

  def quit!(activity)
    self.participations.find_by_activity_id(activity.id).destroy
  end


  #Group membership association methods #####################################
  def member?(group)
    self.group_memberships.find_by_group_id(group.id)
  end

  def join_group!(group)
    self.group_memberships.create!(group_id: group.id)
  end

  def leave_group!(group)
    self.group_memberships.find_by_group_id(group.id).destroy
  end


  #Category subscription methods ###########################################
  def subscribing?(category)
    self.subscriptions.find_by_category_id(category.id)
  end

  def subscribe!(category)
    #subscribe, if not already, and then do the same with all subcategories
    if !subscribing?(category)
      self.subscriptions.create!(category_id: category.id)
    end
    if !category.leaf?
      subcategories = Category.where(parent_category_id: category.id)
      subcategories.each do |subc|
        self.subscribe!(subc)
      end
    end
  end

  def unsubscribe!(category)
    #unsubscribe, if subscribing, and then do the same with all subcategories
    if subscribing?(category)
      self.subscriptions.find_by_category_id(category.id).destroy
    end
    if !category.leaf?
      subcategories = Category.where(parent_category_id: category.id)
      subcategories.each do |subc|
        self.unsubscribe!(subc)
      end
    end
  end

  def reply_to_invite!(invite, response)
    guest = User.find_by_email(invite.guest_email)
    if signed_in? and current_user == guest
      if response == "accept"
        group = Group.find(invite.group_id)
        self.group_memberships.build(group_id: group.id)
        invite.update_attributes(response: 1)
      elsif response == "deny"
        invite.update_attributes(response: 0)
      end
    end
  end

  private
    def add_to_public_group
      public_group = Group.find(1)
      self.join_group!(public_group)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def create
		#add each new user to the public group
		@user = User.find(params[:user])
		@user.join_group!(1)
	end

	def index
		@users = User.all(order: 'users.username')
	end

	def show
		@user = User.find(params[:id])
		@section = params[:section]

		if Rails.env.development? #sqlite3 needs datetime manips
			conditions = ["participations.user_id = ? and DATE(activities.date_and_time) >= DATE(?)", @user.id, Time.now]
			order = ["datetime(activities.date_and_time)"]
		else
			conditions = ["participations.user_id = ? and activities.date_and_time >= ?", @user.id, Time.now]
			order = ["activities.date_and_time"]
		end

		@upcoming_activities = Activity.paginate(per_page: 10, page: params[:page]).all(
				joins: { :participations => { } }, conditions: conditions, order: order )
	end

	def groups
		@title = "Groups"
		@user = User.find(params[:id])
		@section = "groups"
		render "show_user_section"
	end

	def subscriptions
		@title = "Subscriptions"
		@user = User.find(params[:id])
		@section = "subscriptions"
		render "show_user_section"
	end

	def activities
		@title = "Upcoming Activities"
		@user = User.find(params[:id])
		@section = "activities"

		# if Rails.env.development? #sqlite3 needs datetime manips
		# 	conditions = ["participations.user_id = ? and DATE(activities.date_and_time) >= DATE(?)", @user.id, Time.now]
		# 	order = ["datetime(activities.date_and_time)"]
		# else
			conditions = ["participations.user_id = ? and activities.date_and_time >= ?", @user.id, Time.now]
			order = ["activities.date_and_time"]
		# end

		@upcoming_activities = Activity.paginate(per_page: 5, page: params[:page]).all(
				joins: { :participations => { } }, conditions: conditions, order: order )
		render "show_user_section"
	end

	def general_info
		@title = "General Info"
		@user = User.find(params[:id])
		@section = "general_info"
		render "show_user_section"
	end

	def notifications
		@title = "Notifications"
		@user = User.find(params[:id])
		@section = "notifications"
		render "show_user_section"
	end

	def invites
		debugger
		if signed_in? && params[:id].to_i == current_user.id
			@title = "Invites"
			@user = User.find(params[:id])
			@section = "invitations"
			render "show_user_section"
		else
			redirect_to root_path
		end
	end

	def invite_reply
		debugger
		@invite = Invite.find(params[:invite_id])
		@response = params[:response]

		guest = User.find_by_email(@invite.guest_email)
	    if signed_in? and current_user == guest
	      if @response == "accept"
	        group = Group.find(@invite.group_id)
	        current_user.join_group!(group)
	        @invite.update_attributes(response: 1)
	        flash[:success] = "Successfully added group."
	      elsif @response == "deny"
	        @invite.update_attributes(response: 0)
	        flash[:success] = "Successfuly denied invitation."
	      end
	      redirect_to :back
	  	end
    end


	def update
		@user = User.find(params[:id])
		@user.update_attributes(params[:user])
		if @user.save
			flash[:success] = "Successfully updated user"
			sign_in @user
			redirect_to :back
		else
			flash[:error] = "There was a problem: #{@user.errors.full_messages}"
			redirect_to :back
		end
	end

	def destroy
		user = User.find(params[:id])

		#destroy user subscriptions associations
		user.subscriptions.each do |sub|
			sub.destroy
		end

		#destroy user participations associations
		user.participations.each do |par|
			par.destroy
		end

		#destroy user group membership associations
		user.group_memberships.each do |mem|
			mem.destroy
		end

		user.destroy
		flash[:success] = "Your account has successfully been deleted."
		redirect_to root_path
	end
end

app/views/users/_activities.html.erb
<%- model_class = Activity -%>

<% if signed_in? && current_user == @user %>
  <h3>Your Upcoming Activities</h3>
<% else %>
  <h3>Upcoming Activities for <%= @user.username %></h3>
<% end %>


<table class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:where) %></th>
      <th><%= model_class.human_attribute_name(:open) %></th>
    </tr>
  </thead>
  <tbody>
    <% @upcoming_activities.each do |activity| %>
      <tr>
        <td>
          <div>
            <%= Category.find(activity.category_id).name %>
          </div>
        </td>
  	    <td><%= link_to "#{activity.title}", activity_path(activity)%></td>
        <td><%= activity.date_and_time.strftime('%b %d') %></td>
        <td><%= activity.where %></td>
        <% spots_remaining = activity.max_participants - activity.users.count %>
        <td class="open-spots <%= get_activity_row_class(activity) %>">
          <% if spots_remaining > 0 %>
            <p><%= spots_remaining %></p>
          <% else %>
            <p>FULL</p>
          <% end %>
        </td>
  	  </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @upcoming_activities %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">

    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= render 'shared/text_field', field: :username, f: f %><br /><br />
    </div>

    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= render 'shared/text_field', field: :email, f: f %><br /><br />
    </div>

    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
        <%= render 'shared/text_field', field: :first_name, f: f %><br /><br />
    </div>

    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= render 'shared/text_field', field: :last_name, f: f %><br /><br />
    </div>
    
    <%= f.label :age, :class => 'control-label' %>
    <div class="controls">
      <%= render 'shared/number_field', field: :age, f: f %><br /><br />
    </div>
    
    <%= f.label :zipcode, :class => 'control-label' %>
    <div class="controls">
      <%= render 'shared/text_field', field: :zipcode, f: f %><br /><br />
    </div>

    <% if signed_in? && @user == current_user %>
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password %><br /><br />
      </div>

      <%= f.label :password_confirmation, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation %><br /><br /><br />
      </div>
    <% end %>



    <div class="form-actions">
      <%= link_to t('.back', :default => t("helpers.links.back")),
                    :back, :class => 'btn'  %>
      <% if (signed_in? && @user == current_user) || current_user.admin? %>
        <%= f.submit "Update", :class => 'btn btn-primary' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                user_path(@user),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure you want to delete your account?  All your previous data will be lost.')) },
                :class => 'btn btn-danger far-right' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_general_info.html.erb
<div class="page-header">
	<% if signed_in? && current_user == @user %>
	  <h3>Your Info</h3>
	<% else %>
	  <h3>Info for <%= @user.username %></h3>
	<% end %>
</div>

<%= render :partial => 'form' %>

app/views/users/_groups.html.erb
<div class="page-header">
  <% if signed_in? && current_user == @user %>
    <h3>Your Groups</h3>
  <% else %>
    <h3>Groups for <%= @user.username %></h3>
  <% end %>
</div>

<% if @user.groups.count > 1 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <% if signed_in? && @user == current_user %>
        	<th><%=t '.actions', :default => t("helpers.actions") %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @user.groups.each do |group| %>
        <% if group.id != 1 %>
    	    <tr class=<%= get_group_row_class(group) %>>
    	      <td><%= link_to group.name, group_path(group) %>
              <% if !group.open_to_public? %>
                <span class="unbold">(private)</span>
              <% end %>
            </td>
            <td>
            	<% if signed_in? && @user == current_user %>
                <%= form_for(current_user.group_memberships.find_by_group_id(group.id),
                	                  html: { method: :delete, class: "inline-form" }) do |f| %>
    				      <%= image_submit_tag "leave.png", class: "subscribe-button inline", title: "leave group" %>
                <% end %>
    			    <% end %>
            </td>
    	    </tr>
        <% end %>
  	  <% end %>
    </tbody>
  </table>
<% elsif signed_in? && @user == current_user %>
  <p>You are not currently a member of any group.  To join a group, go to the group page and search for groups.  When you find a group you would like to join, simply click on the red plus sign.  You're then a member of that group!</p>
<% end %>

app/views/users/_invites.html.erb
<div class="page-header">
  <h3>Your Pending Invitations</h3>
</div>

<% pending_user_invites = Invite.where(guest_email: @user.email, response: nil) %>

<% if pending_user_invites.count > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Group</th>
        <% if signed_in? && @user == current_user %>
        	<th><%=t '.actions', :default => t("helpers.actions") %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% pending_user_invites.each do |invite| %>
        <% group = Group.find_by_id(invite.group_id) %>
  	    <tr>
  	      <td><%= link_to group.name, group_path(group) %></td>
          <td>
          	<% if signed_in? && @user == current_user %>

              <%= form_tag invite_reply_user_path, class: "inline" do %>
                <%= hidden_field_tag :invite_id, invite.id %>
                <%= hidden_field_tag :response, "accept" %>
                <%= image_submit_tag "join.jpg", class: "subscribe-button inline", title: "accept" %>
              <% end %>

              <%= form_tag invite_reply_user_path, class: "inline" do %>
                <%= hidden_field_tag :invite_id, invite.id %>
                <%= hidden_field_tag :response, "deny" %>
                <%= image_submit_tag "leave.png", class: "subscribe-button inline", title: "deny" %>
              <% end %>

  			    <% end %>
          </td>
  	    </tr>
  	  <% end %>
    </tbody>
  </table>
<% elsif signed_in? && @user == current_user %>
  <p>You do not currently have any outstanding group invitations.</p>
<% end %>

app/views/users/_notifications.html.erb
<div class="page-header">
  <% if signed_in? && current_user == @user %>
    <h3>Your Notifications</h3>
  <% else %>
    <h3>Notifications for <%= @user.username %></h3>
  <% end %>
</div>

<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <!--- <%= f.label "New activity", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :notf_new_activity, checked_value: true, unchecked_value: false %><br /><br />
    </div> -->
    <%= f.label "Max public distance", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :public_distance_notf_max, default: 4000, min: -1, class: "distance-entry" %><br />
      You will not be notified if a <span class="bold">PUBLIC</span> activity is more than this distance (miles) away from you.<br />
      Enter "-1" to not be notified about <span class="bold">PUBLIC</span> activities at all.<br /><br />
    </div>
    <%= f.label "New comment", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :notf_new_comment, checked_value: true, unchecked_value: false %><br /><br />
    </div>
    <%= f.label "Activity turns 'ON'", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :notf_activity_turns_on, checked_value: true, unchecked_value: false %><br /><br />
    </div>
  </div>

  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                    :back, :class => 'btn'  %>
    <% if signed_in? && @user == current_user %>
      <%= f.submit "Update", :class => 'btn btn-primary' %>
    <% end %>
  </div>
<% end %>

app/views/users/_subscriptions.html.erb
<div class="page-header">
  <% if signed_in? && current_user == @user %>
    <h3>Your Subscriptions</h3>
  <% else %>
    <h3>Subscriptions for <%= @user.username %></h3>
  <% end %>
</div>

<% if @user.subscriptions.count > 0 %>
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <% if signed_in? && @user == current_user %>
	      	<th><%=t '.actions', :default => t("helpers.actions") %></th>
	      <% end %>
	    </tr>
	  </thead>
	  <tbody>
	    <% @user.subscriptions.each do |sub| %>
		    <tr>
		      <% category = Category.find(sub.category_id) %>
		      <td><%= category.name %></td>
	          <td>
	          	<% if signed_in? and current_user == @user %>
	          	  <%= form_for(@user.subscriptions.find_by_category_id(category.id),
	                    html: { method: :delete, class: "inline-form" }) do |f| %>
	          		<%= image_submit_tag "is_subscribing.png", class: "subscribe-button", title: "unsubscribe" %>
	        	  <% end %>
	        	<% end %>
	          </td>
		    </tr>
		  <% end %>
	  </tbody>
	</table>
<% elsif @user == current_user %>
	<p>You currently have no subscriptions.  To subscribe, go to the activities page and browse through the categories.  When you find one you are interested in, click on the rss icon next to it.  You will then be subscribed.  And yes, you can unsubscribe at anytime.</p>
<% else %>
	<p>This user has no subscriptions.</p>
<% end %>

app/views/users/_user_actions.html.erb
<% if signed_in? %>
	<span class="action-buttons">
	
		<%= link_to t('.edit', :default => t("helpers.links.edit")),
		              general_info_user_path(user), :class => 'btn btn-mini' %>
		<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
		          user_path(user),
		          :method => :delete,
		          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
		          :class => 'btn btn-mini btn-danger' %>
	</span>
<% end %>

app/views/users/_user_activities.html.erb
<%- model_class = Activity -%>

<h3>Upcoming Activities</h3>


<table class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:where) %></th>
      <th><%= model_class.human_attribute_name(:open) %></th>
    </tr>
  </thead>
  <tbody>
    <% @upcoming_activities.each do |activity| %>
      <tr>
        <td>
          <div>
            <%= Category.find(activity.category_id).name %>
          </div>
        </td>
  	    <td><%= link_to "#{activity.title}", activity_path(activity)%></td>
        <td><%= activity.date_and_time.strftime('%b %d') %></td>
        <td><%= activity.where %></td>
        <% spots_remaining = activity.max_participants - activity.users.count %>
        <td class="open-spots <%= get_activity_row_class(activity) %>">
          <% if spots_remaining > 0 %>
            <p><%= spots_remaining %></p>
          <% else %>
            <p>FULL</p>
          <% end %>
        </td>
  	  </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @upcoming_activities %>

app/views/users/_user_groups.html.erb
<div class="page-header">
  <h3>Groups</h3>
</div>

<% if @user.groups.count > 1 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <% if signed_in? && @user == current_user %>
        	<th><%=t '.actions', :default => t("helpers.actions") %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @user.groups.each do |group| %>
        <% if group.id != 1 %>
    	    <tr class=<%= get_group_row_class(group) %>>
    	      <td><%= group.name %></td>
            <td>
            	<% if signed_in? && @user == current_user %>
                <%= form_for(current_user.group_memberships.find_by_group_id(group.id),
                	                  html: { method: :delete, class: "inline-form" }) do |f| %>
    				      <%= image_submit_tag "leave.png", class: "subscribe-button inline", title: "leave group" %>
                <% end %>
    			    <% end %>
            </td>
    	    </tr>
        <% end %>
  	  <% end %>
    </tbody>
  </table>
<% elsif signed_in? && @user == current_user %>
  <p>You are not currently a member of any group.  To join a group, go to the group page and search for groups.  When you find a group you would like to join, simply click on the red plus sign.  You're then a member of that group!</p>
<% end %>

app/views/users/_user_subscriptions.html.erb
<div class="page-header">
  <h3>Subscriptions</h3>
</div>

<% if @user.subscriptions.count > 0 %>
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <% if signed_in? && @user == current_user %>
	      	<th><%=t '.actions', :default => t("helpers.actions") %></th>
	      <% end %>
	    </tr>
	  </thead>
	  <tbody>
	    <% @user.subscriptions.each do |sub| %>
		    <tr>
		      <% category = Category.find(sub.category_id) %>
		      <td><%= category.name %></td>
	          <td>
	          	<% if signed_in? and current_user == @user %>
	          	  <%= form_for(@user.subscriptions.find_by_category_id(category.id),
	                    html: { method: :delete, class: "inline-form" }) do |f| %>
	          		<%= image_submit_tag "is_subscribing.png", class: "subscribe-button", title: "unsubscribe" %>
	        	  <% end %>
	        	<% end %>
	          </td>
		    </tr>
		  <% end %>
	  </tbody>
	</table>
<% elsif @user == current_user %>
	<p>You currently have no subscriptions.  To subscribe, go to the activities page and browse through the categories.  When you find one you are interested in, click on the rss icon next to it.  You will then be subscribed.  And yes, you can unsubscribe at anytime.</p>
<% else %>
	<p>This user has no subscriptions.</p>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>

<%- model_class = User -%>
<div class="main-area">
  <div class="span3">
    <h1 class="row">
      <%=t '.title', :default => model_class.model_name.human.pluralize %>
    </h1>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:username) %></th>
        <th><%= model_class.human_attribute_name(:email) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to "#{user.username}", general_info_user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= user.created_at %></td>
          <td>
            <%= render partial: 'user_actions', locals: { user: user } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if signed_in? %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_group_path,
                :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, 'User Profile') %>

<%- model_class = User -%>
<div id="user-info">
	<div class="row">
		<div class="span8">
			<div class="main-area">
			  <h3>General Info: <%= @user.username %></h3>
				<%= render :partial => 'form' %>
			</div>
		</div>
	</div>
</div>
<br />


<div class="row">
	<div class="span8">
		<div class="main-area"?>
			<%= render 'user_activities' %>
		</div>
	</div>
</div>
<br />

<div class="row">
	<div class="span4">
		<div id="user-groups", class="main-area">
			<%= render 'user_groups' %>
		</div>
	</div>
	<div class="span4 main-area" %>
		<%= render 'user_subscriptions' %>
	</div>
</div>

app/views/users/show_user_section.html.erb
<div class="row profile-page">
	<div class="navbar navbar-inner container"> 
		<ul class="nav">
			<li><%= link_to "General Info", general_info_user_path(@user) %></li>
			<li><%= link_to "Groups", groups_user_path(@user) %></li>
			<li><%= link_to "Subscriptions", subscriptions_user_path(@user) %></li>
			<li><%= link_to "Upcoming Activities", activities_user_path(@user) %></li>
			<% if signed_in? && current_user == @user %>
				<li><%= link_to "Notifications", notifications_user_path(@user) %></li>
				<li><%= link_to "Invites", invites_user_path(@user) %></li>
			<% end %>
		</ul>
	</div>
</div>

<div class="container">
	<div class="span11">
		<div class="main-area"?>
			<%  if @section == "groups" %>
				<%= render "groups" %>
			<% elsif @section == "subscriptions" %>
				<%= render "subscriptions" %>
			<% elsif @section == "notifications" %>
				<%= render "notifications" %>
			<% elsif @section == "activities" %>
				<%= render "activities" %>
			<% elsif @section == "general_info" %>
				<%= render "general_info" %>
			<% elsif @section == "invitations" %>
				<%= render "invites" %>
			<% end %>
		</div>
	</div>
</div>