config/routes.rb
Unite::Application.routes.draw do
  get "static_pages/help"

  devise_for :users

  resources :users do
    member do
      get :general_info, :groups, :subscriptions, :activities, :notifications, :invites
      post :invite_reply
    end
  end

  resources :categories
  resources :subscriptions, only: [:create, :destroy]
  resources :activities 
  resources :participations, only: [:create, :destroy]
  resources :groups do
    member do
      post :invite
    end
  end
  resources :group_memberships, only: [:create, :destroy]  
  resources :comments

  root to: "activities#index", category_id: 13
  match '/help', to: 'static_pages#help'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :title, :description, :its_on, :max_participants, :min_participants, 
                  :date_and_time, :where, :zipcode, :category_id, :group_ids

  geocoded_by :zipcode
  after_validation :geocode

  has_one :location

  has_many :participations, foreign_key: "activity_id"
  has_many :users, through: :participations

  has_many :activity_group_relations, foreign_key: "activity_id"
  has_many :groups, through: :activity_group_relations

  has_many :comments

  after_create :auto_add_creator_to_participants

  validates :title,				      presence: true, uniqueness: { case_sensitive: false }
  validates :min_participants, 	presence: true
  validates :date_and_time,			presence: true
  VALID_ZIPCODE_REGEX = %r(\b[0-9]{5}(?:-[0-9]{4})?\b)
  validates :zipcode,           presence: true, format: { with: VALID_ZIPCODE_REGEX },
                                numericality: { greater_than: 9999, less_than: 100000 }

  private
    def auto_add_creator_to_participants
      creator = User.find(self.creator_id)
      creator.participate!(self)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,   #added by devise
  				  :first_name, :last_name, :username, :age, :zipcode,		           #general info
            :public_distance_notf_max,  #max distance to notify for public activities
            :notf_new_activity, :notf_activity_turns_on, :notf_new_comment   #notifications

  geocoded_by :zipcode
  after_validation :geocode
  				 
  #Activity participation associations
  has_many :participations, foreign_key: "user_id"
  has_many :activities, through: :participations

  #Group membership associations
  has_many :group_memberships, foreign_key: "member_id"
  has_many :groups, through: :group_memberships

  #Category subscription associations
  has_many :subscriptions, foreign_key: "subscriber_id"
  has_many :categories, through: :subscriptions

  #Comment associations
  has_many :comments

  #validations
  validates :username,  			presence: true,  uniqueness: { case_sensitive: false }
  validates :age,       			presence: true
  validates :zipcode,   			presence: true

  after_create :add_to_public_group

  # attr_accessible :title, :body

  #Activity association methods ##############################################
  def participating?(activity)
    self.participations.find_by_activity_id(activity.id)
  end

  def participate!(activity)
    self.participations.create!(activity_id: activity.id)
  end

  def quit!(activity)
    self.participations.find_by_activity_id(activity.id).destroy
  end


  #Group membership association methods #####################################
  def member?(group)
    self.group_memberships.find_by_group_id(group.id)
  end

  def join_group!(group)
    self.group_memberships.create!(group_id: group.id)
  end

  def leave_group!(group)
    self.group_memberships.find_by_group_id(group.id).destroy
  end


  #Category subscription methods ###########################################
  def subscribing?(category)
    self.subscriptions.find_by_category_id(category.id)
  end

  def subscribe!(category)
    #subscribe, if not already, and then do the same with all subcategories
    if !subscribing?(category)
      self.subscriptions.create!(category_id: category.id)
    end
    if !category.leaf?
      subcategories = Category.where(parent_category_id: category.id)
      subcategories.each do |subc|
        self.subscribe!(subc)
      end
    end
  end

  def unsubscribe!(category)
    #unsubscribe, if subscribing, and then do the same with all subcategories
    if subscribing?(category)
      self.subscriptions.find_by_category_id(category.id).destroy
    end
    if !category.leaf?
      subcategories = Category.where(parent_category_id: category.id)
      subcategories.each do |subc|
        self.unsubscribe!(subc)
      end
    end
  end

  def reply_to_invite!(invite, response)
    guest = User.find_by_email(invite.guest_email)
    if signed_in? and current_user == guest
      if response == "accept"
        group = Group.find(invite.group_id)
        self.group_memberships.build(group_id: group.id)
        invite.update_attributes(response: 1)
      elsif response == "deny"
        invite.update_attributes(response: 0)
      end
    end
  end

  private
    def add_to_public_group
      public_group = Group.find(1)
      self.join_group!(public_group)
    end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :activity_creator, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :min_one_group, only: [:create, :update]

  def index
    #the params[:category_id] is the id of the category that was just clicked on
    all_category_ids = get_all_subcategory_ids(params[:category_id])
    if signed_in?
      group_ids_to_use = current_user.group_ids
      if params[:distance]
        if params[:distance] == "" || params[:distance] == "false"
          @distance = false
        else
          @distance = params[:distance]
        end
      else
        @distance = false
      end
    else
      group_ids_to_use = [1] #only show public activities if not signed in (0 keeps it an array)
      @distance = false
    end 

    conditions = ["groups.id IN (?) and activities.category_id IN (?) and
                    activities.date_and_time >= ?", group_ids_to_use, all_category_ids, Time.now ]
    order = ["activities.date_and_time"]

    if @distance
      @activities = Activity.paginate(per_page: 10, page: params[:page]).near(current_user, @distance).all(
                                  joins: {:groups => :activity_group_relations}, 
                                  group: 'activities.id', 
                                  conditions: conditions, 
                                  order: order )      
    else
      @activities = Activity.paginate(per_page: 10, page: params[:page]).all(
                                  joins: {:groups => :activity_group_relations}, 
                                  group: 'activities.id', 
                                  conditions: conditions, 
                                  order: order )
    end

    @categories = Category.order("name").where(parent_category_id: params[:category_id])
    if params[:category_id]
      @current_directory = Category.find(params[:category_id])
      parent_directory_id = @current_directory.parent_category_id
      if parent_directory_id
        @parent_directory = Category.find(parent_directory_id)
      else
        @parent_directory = nil
      end
    end
  end

  def new
    @activity = Activity.new
    @category = Category.find(params[:category_id])
  end

  def create
    @activity = Activity.new(params[:activity])
    @activity.creator_id = current_user.id
    @category = Category.find(@activity.category_id)
    if @activity.save
      flash[:success] = "Successfully created activity: #{@activity.title}"
      redirect_to activities_path(category_id: @activity.category_id)
      send_emails_for_new_activity
    else
      flash.now[:error] = "there was a problem: #{@activity.errors.full_messages}"
      render 'new'
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @category = Category.find(@activity.category_id)
    @creator = User.find(@activity.creator_id)
    @previous_category_id = params[:last_category_id]
    @comments = Comment.where(activity_id: @activity.id).paginate(per_page: 25, page: params[:page])
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    params[:activity][:group_ids] ||= []
    @activity = Activity.find(params[:id])
    if @activity.update_attributes(params[:activity])
      flash[:success] = "Activity updated"
      check_if_its_on(@activity)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    activity = Activity.find(params[:id])

    #destroy all participation associations for this activity
    activity.participations.each do |participation|
      participation.destroy
    end

    #destroy all activity-group-relation associations for this activity
    activity.activity_group_relations.each do |agr|
      agr.destroy
    end

    activity.destroy
    flash[:success] = "Activity deleted"
    redirect_to root_path
  end

  private
    def activity_creator
      activity = Activity.find(params[:id])
      creator = User.find(activity.creator_id)
      redirect_to(root_path) unless creator == current_user || current_user.admin?
    end

    def check_if_its_on(activity)
      if !activity.its_on? && activity.users.count >= activity.min_participants
        activity.update_attributes(its_on: true)
        send_emails_for_its_on(activity)
      elsif activity.its_on? && activity.users.count < activity.min_participants
        activity.update_attributes(its_on: false)
      end
    end

    def min_one_group
      if !params[:activity][:group_ids]
        flash[:error] = "An activity must belong to at least 1 group."
        redirect_to :back
      end
    end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
	def category_activities(category_id)
		#given a category this will return all the activites that fall in that category
		current_category = Category.find(category_id)
		all_category_ids = get_all_subcategory_ids(category_id)
		if !signed_in?
			#return all activities in all groups
			return Activity.where(category_id: all_category_ids)
		else
			#only return activities for user groups
			conditions = "groups.id IN (?) AND activities.category_id IN (?) AND 
						  activities.date_and_time > (?)", current_user.group_ids, all_category_ids, Time.now

			if @distance
				return Activity.near(current_user, @distance).all(joins: {:groups => :activity_group_relations}, 
	                           		group: 'activities.id', 
	                           		conditions: conditions )
			else
				return Activity.all(joins: {:groups => :activity_group_relations}, 
	                           		group: 'activities.id', 
	                           		conditions: conditions )
			end
		end
	end

	def get_all_subcategory_ids(category_id)
		#given a category this will return the list of all its subcategory ids
		current_category = Category.find(category_id)
		if current_category.leaf # base case
			return [category_id.to_i]
		else
			subcategories = Category.where(parent_category_id: category_id)
			all_category_ids = []
			subcategories.each do |subc|
				all_category_ids += get_all_subcategory_ids(subc.id)
			end
			return all_category_ids
		end
	end	

	def get_activity_category_image(activity)
		category = Category.find(activity.category_id)
		image_tag("#{category.image_path}", height: 35, width: 35, title: "#{category.name}")
	end

	def get_nav_item_class(item)
		if params[:controller] == item
			"active"
		elsif params[:controller] == "static_pages"
			if params[:action] == item
				"active"
			end
		end
	end

	def get_activity_row_class(activity)
		if activity.its_on? 
			if activity.users.count < activity.max_participants
	          "its-on-open"
	        else
	          "its-on-full"
	        end
	    else
	    	"its-off"
	    end
    end

    def bold_activity?(activity)
    	if signed_in? && current_user.participating?(activity)
    		"bold"
    	end
    end

    def send_emails_for_new_activity
    	sent_to = []
    	@activity.groups.each do |group|
    		group.members.each do |member|
    			if !sent_to.include? member.email
    				if member.notf_new_activity
    					for sub in member.subscriptions do
    						if sub.category_id == @category.id
    							if group.id == 1 #public group
	    							if member.public_distance_notf_max != -1
	    								if @activity.distance_to(member) < member.public_distance_notf_max
						    				sent_to += [member.email]
						    				UserMailer.new_activity(member, @activity, @category, group).deliver
						    				break
						    			end
						    		end
					    		else
					    			sent_to += [member.email]
						    		UserMailer.new_activity(member, @activity, @category, group).deliver
						    		break
					    		end
			    			end
		    			end
	    			end
    			end
    		end
    	end
    end

    def send_emails_for_its_on(activity)
    	activity.users.each do |participant|
    		if participant.notf_activity_turns_on?
    			UserMailer.its_on(participant, activity).deliver
    		end
    	end
    end
    
end

app/views/activities/_activities_list.html.erb
<%- model_class = Activity -%>

<div class="main-area">
  <% if @current_directory %>
    <h2> Activities - <%= @current_directory.name.capitalize %></h2>
  <% else %>
    <h2> Activities </h2>
  <% end %>
  <div class="activity-legend">
    <p class="inline">
      *** Displaying all activities for all your groups (whether subscribing or not). *** <br />
      *** If it's <span class="its-on-open">green</span>, 
      then <span class="its-on-text">IT'S ON!</span> and spots remain.
      If it's <span style="color: red;">red</span> then it's full. ***<br />
    </p>
  </div>
  <hr />
  <% if @activities.count > 0 %>
    <table class="table">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:category) %></th>
          <th><%= model_class.human_attribute_name(:title) %></th>
          <th><%= model_class.human_attribute_name(:date) %></th>
          <th><%= model_class.human_attribute_name(:distance) %></th>
          <th><%= model_class.human_attribute_name(:open) %></th>
        </tr>
      </thead>
      <tbody>
        <% @activities.each do |activity| %>
          <tr class=<%= get_activity_row_class(activity) %>>
            <td>
              <div>
                <!-- <%= get_activity_category_image(activity) %> -->
                <%= Category.find(activity.category_id).name %>
              </div>
            </td>
      	    <td><%= link_to "#{activity.title}", activity_path(activity)%></td>
            <td><%= activity.date_and_time.strftime('%b %d') %></td>
            <% if signed_in? %>
              <td><%= "#{activity.distance_to(current_user).round(0)} mi" %></td>
            <% else %>
              <td>unknown</td>
            <% end %>
            <% spots_remaining = activity.max_participants - activity.users.count %>
            <td class="open-spots">
              <% if spots_remaining > 0 %>
                <p><%= spots_remaining %></p>
              <% else %>
                <p>FULL</p>
              <% end %>
            </td>
      	  </tr>
        <% end %>
      </tbody>
    </table>

     <%= will_paginate @activities %>
  <% else %>
    <p class="bold">There are no activities to show.</p><br />
  <% end %>

  <% if signed_in? %>

    Only show activities within 
    <%= form_tag activities_path, method: 'get', class: "inline" do %>
        <%= number_field_tag :distance, params[:distance], class: "distance-entry" %>
        <%= hidden_field_tag :category_id, params[:category_id] %>
        miles from me 
        <%= submit_tag "Search", name: nil, class: "btn btn-mini btn-primary" %>
    <% end %>
    <br /><br />

    <% if @current_directory %>
    	<%= link_to t('.new', :default => t("helpers.links.new")),
    	            new_activity_path(category_id: @current_directory.id),
    	            :class => 'btn btn-primary' %>
    <% else %>
      <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_activity_path(),
                  :class => 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>

app/views/activities/_activity_details.html.erb
<%- model_class = Activity -%>
<div class="main-area">
  <h2>Details</h2>

  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
    <dd><%= @activity.title %></dd>
    <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
    <dd><%= @activity.description %></dd>
    <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
    <dd><%= @activity.date_and_time.to_date %></dd>
    <dt><strong><%= model_class.human_attribute_name(:time) %>:</strong></dt>
    <dd><%= @activity.date_and_time.strftime('%I:%M %p') %></dd>
    <dt><strong><%= model_class.human_attribute_name(:zipcode) %>:</strong></dt>
    <dd><%= @activity.zipcode %></dd>
    <dt><strong><%= model_class.human_attribute_name(:distance) %>:</strong></dt>
    <dd><%= "#{@activity.distance_to(current_user).round(2)} mi" %></dd>
    <dt><strong><%= model_class.human_attribute_name(:location_details) %>:</strong></dt>
    <dd><%= @activity.where %></dd>
    <dt><strong><%= model_class.human_attribute_name(:min_participants) %>:</strong></dt>
    <dd><%= @activity.min_participants %></dd>
    <dt><strong><%= model_class.human_attribute_name(:max_participants) %>:</strong></dt>
    <dd><%= @activity.max_participants %></dd>
    <dt><strong><%= model_class.human_attribute_name(:its_on) %>:</strong></dt>
    <dd><%= @activity.its_on %></dd>
    <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
    <dd><%= @category.name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:creator) %>:</strong></dt>
    <dd><%= @creator.username %></dd>
  </dl>

  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                :back, :class => 'btn'  %>
    <% if signed_in? %>
      <% if (current_user == @creator) || current_user.admin? %>
        <%= link_to "edit", edit_activity_path(@activity), :class => 'btn' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    activity_path(@activity),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/activities/_activity_groups.html.erb
<%- model_class = Activity -%>
<div class="main-area">
	<table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:groups) %></th>
      </tr>
    </thead>
    <tbody>
      <% @activity.groups.each do |group| %>
  	  <tr>
  	  	<td><%= link_to_group(group) %></td>
  	  </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/activities/_all_comments.html.erb
<div class="main-area">
  <div class="bold"> Comments </div><br />

  <% if signed_in? %>
    <%= form_for(@activity.comments.build(activity_id: @activity.id),
                  html: {class: "inline-form"}) do |f| %>
      <%= f.text_area :body, cols: 5, rows: 3 %>
      <div><%= f.hidden_field :activity_id %></div>
      <%= f.submit "POST", class: "btn btn-primary inline" %>
    <% end %>
  <% else %>
    <p>You must be signed in to add a comment</p>
  <% end %>
  <br />
  <br />

  <% if @comments.any? %>
    <hr />
    <ol class="comments">
      <%= render @comments %>
    </ol>
    <%= will_paginate @comments %>
  <% end %>
</div>

app/views/activities/_category_navigation.html.erb
<%- model_class = Category -%>

<div class="main-area">
  <h2>Feeds</h2>
  * = Contains subfeeds<br /><br />
  <% if @parent_directory %>
  	<%= link_to "Back to #{@parent_directory.name}", 
  				activities_path(category_id: @parent_directory.id, distance: @distance) %>
  <% end %>
  <table class="table">
    <thead>
      <tr>
        <% if @current_directory %>
        	<th><%= "#{model_class.human_attribute_name(@current_directory.name)} (#{category_activities(@current_directory.id).size})" %></th>
        <% else %>
        	<th>Main</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <%= render partial: "category_row", locals: { category: category } %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if signed_in? and current_user.admin? %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_category_path,
                :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/activities/_category_row.html.erb
<% if !category.leaf? %>
  <% display_name = "#{category.name}*" %>
<% else %>
  <% display_name = "#{category.name}" %>
<% end %>

<td><%= link_to "#{display_name}", activities_path(category_id: category, distance: @distance) %>
  <%= " (#{category_activities(category.id).size})" %>
  <span id="category-icon">
    <% if signed_in? %>
      <% if current_user.subscribing?(category) %>
        <!-- if they are subscribing, we show the green image and make it unsubscribe if clicked -->
        <%= form_for(current_user.subscriptions.find_by_category_id(category.id),
                    html: { method: :delete, class: "inline-form" }) do |f| %>
          <%= image_submit_tag "is_subscribing.png", class: "subscribe-button", title: "unsubscribe" %>
        <% end %>
      <% else %>
        <!-- if they are not subscribing, we show the grey image and make it subscribe if clicked -->
        <%= form_for(current_user.subscriptions.build(category_id: category.id),
                    html: { class: "inline-form"}) do |f| %>
          <div><%= f.hidden_field :category_id %></div>
          <%= image_submit_tag "is_not_subscribing.png", class: "subscribe-button", title: "subscribe" %>
        <% end %>        
      <% end %>
    <% end %>
  </span><br />
</td>

app/views/activities/_drop_button.html.erb
<%= form_for(current_user.participations.find_by_activity_id(@activity),
             html: { method: :delete }) do |f| %>
  <%= f.submit "DROP ACTIVITY", class: "btn btn-large" %>
<% end %>

app/views/activities/_form.html.erb
<%= form_for @activity, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :date_and_time, :class => 'datetime_select' , default: 1.hour.from_now%>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :time, :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :date_and_time, :class => 'datetime_select' , ignore_date: true, 
                        ampm: true, minute_step: 5, default: 1.hour.from_now%>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :zipcode, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :zipcode, :class => 'number_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :location_details, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :where, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :min_participants, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :min_participants, :class => 'number_field', :in => 0..1000000, default: 0 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :max_participants, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :max_participants, :class => 'number_field', :in => 0..1000000, default: 0 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :category_id, :class => 'control-label' %>
    <div class="controls">
      <% if @category %> 
        <%= f.collection_select :category_id, Category.order('name ASC').where(leaf: true), :id, :name, 
            :class => 'number_field', selected: @category.id %>
      <% else %> 
        <%= f.collection_select :category_id, Category.order('name ASC').where(leaf: true), :id, :name, 
            :class => 'number_field' %>
      <% end %>
    </div>
  </div>
  <br />
  <h3>Groups<h3>

  <% current_user.groups.each do |group| %>
    
      <div class="row">
        <div class="span5 offset1">
          <% if group.id == 1 %>
            <%= check_box_tag :group_ids, group.id, @activity.groups.include?(group), 
                              name: 'activity[group_ids][]', html: { class: "inline" }, checked: true %>
          <% else %>
            <%= check_box_tag :group_ids, group.id, @activity.groups.include?(group), 
                              name: 'activity[group_ids][]', html: { class: "inline" } %>
          <% end %>
          <span id="category-xbox"> <%= group.name %> </span>
        </div>
      </div>
    
  <% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                root_path, :class => 'btn' %>
  </div>
<% end %>

app/views/activities/_join_button.html.erb
<%= form_for(current_user.participations.build(activity_id: @activity.id)) do |f| %>
  <div><%= f.hidden_field :activity_id %></div>
  <%= f.submit "JOIN ACTIVITY", class: "btn btn-large btn-primary" %>
<% end %>

app/views/activities/edit.html.erb
<% provide(:title, 'Edit Activity') %>
<%- model_class = Activity -%>
<div class="main-area">
  <h3>Edit Activity</h3>

	<%= render :partial => 'form' %>
</div>

app/views/activities/index.html.erb
<% provide(:title, 'Activities') %>

<!-- <div class="instruction-question">How do activities work?</div>
<p>Each activity has a set number of min and max participants that can join.  Users join an activity by first clicking on the activity title in the list below, and then clicking the "JOIN ACTIVITY" button in the activity details page.  Once the min number of participants has been met, the activity becomes real and will actually take place, or as we like to say, "<span class="its-on-text">IT'S ON!</span>".  You can see how many spots remain for an activity by looking at the 'Open' column in the table below.  All activities have a max number of participants, and are on a "first come, first served" basis, so be quick and don't miss your chance to participate in the next big event!</p><br /> -->

<span class="instruction-question">How does it work?</span></span><br />
<p><span class="its-on-text">IT'S ON!</span> is simply an online hub to organize activities with others in your area.  Want to set up a pick-up game of basketball after school or after work? <span class="its-on-text">IT'S ON!</span> is the perfect tool to help you do just that.  All you need to do is subscribe to the feeds (activities) that your're interested in.  Then when a local activity pops up in a feed that you're subscribing to, you'll be notified right away, and if you want in on the fun, you simply click 'Join'.  If enough people join the activity it becomes real and the activity will take place, or as we like to say, <span class="its-on-text">IT'S ON!</span>.  It's that simple.<br />

<div class="row">
	<div class="span10 offset1">
		<%= image_tag("how_it_works.png", alt: "how it works") %>
	</div>
</div><hr />



<div class="row">
	<aside class="span3">
		<%= render "category_navigation" %>
		<br />
		<% if signed_in? and current_user.subscriptions.count == 0 %>
			<span class="bold">You are currently not subscribing to any categories!</span>
			<span>  To get the most out of </span>
			<span class="its-on-text">IT'S ON!</span><span>, subscribe to categories that you're interested in by clicking on the rss icons.  If it's green, then you're subscribing.  You will be notified when activities come up in your subscriptions.
		<% end %>
		<br />
	</aside>


	<div class="span9">
		<%= render "activities_list" %>
	</div>
</div>
<br />
<br />
<br />

app/views/activities/new.html.erb
<% provide(:title, 'New Activity') %>

<%- model_class = Activity -%>

<div class="instruction-question">Creating a new activity...</div>
<p> All the basic info for the activity must be filled in.  <span class="bold">Also, every activity must belong to at least 1 group.</span> By default, every activity is open to the 'public' group.  If you do not want this activity to be open to the public, make sure you uncheck the "public" checkbox in the groups section.</p><br />

<div class="main-area">
  <h3>General Info</h3>
	<%= render :partial => 'form' %>
</div>

app/views/activities/show.html.erb
<% provide(:title, 'Activity Details') %>

<div class="instruction-question">How do activities work?</div>
<p>Each activity has a set number of min and max participants that can join.  Users join an activity by clicking on the "JOIN ACTIVITY" button in the activity details page (as seen below).  Once the min number of participants has been met, the activity becomes real and will actually take place, or as we like to say, "<span class="its-on-text">IT'S ON!</span>".  All activities have a max number of participants, and are on a "first come, first served" basis, so be quick and don't miss your chance to participate in the next big event!</p><br />


<div class="row">
	<div class="span5">
	  <%= render "activity_details" %>
	</div>

	<div class="span5 offset1">
	  <%= render "activity_users" %>
	</div>
</div>
<br />

<div class="row">
	<div class="span5">
		<%= render "activity_groups" %>
	</div>
</div>
<br />

<div class="row">
	<div class="span11">
		<%= render "all_comments" %>
	</div>
</div>

app/views/activities/update.html.erb
<h1>Activities#update</h1>
<p>Find me in app/views/activities/update.html.erb</p>